import { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Save, ArrowLeft, Loader2, Table2, FileText, Search,
  Check, X, Trash2,
} from 'lucide-react';
import api, { calendarAPI, googleWorkspaceAPI } from '../../services/api';

const API_BASE = window.location.origin + '/api/google-workspace';

// ─── Tool builder helpers ───────────────────────────────────

function buildSheetsTools(userId, integrationId, spreadsheetId, spreadsheetName) {
  const qs = `userId=${userId}&integrationId=${integrationId}`;
  const base = API_BASE;

  const tools = [
    {
      name: 'list_spreadsheets',
      autoGenerated: true,
      description: 'Search or browse Google Spreadsheets accessible to the user.',
      url: `${base}/sheets/list?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'query', type: 'string', description: 'Optional search term to filter spreadsheets by name', required: false },
      ],
    },
    {
      name: 'get_spreadsheet_info',
      autoGenerated: true,
      description: `Get metadata for a spreadsheet including all sheet/tab names. ${spreadsheetId ? `Default spreadsheet: "${spreadsheetName}" (ID: ${spreadsheetId})` : ''}`,
      url: `${base}/sheets/get?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'spreadsheetId', type: 'string', description: `The spreadsheet ID.${spreadsheetId ? ` Default: ${spreadsheetId}` : ''}`, required: true },
      ],
    },
    {
      name: 'read_sheet_data',
      autoGenerated: true,
      description: `Read data from a Google Sheet using A1 notation (e.g. "Sheet1!A1:D10"). ${spreadsheetId ? `Default spreadsheet: "${spreadsheetName}" (ID: ${spreadsheetId})` : ''}`,
      url: `${base}/sheets/read?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'spreadsheetId', type: 'string', description: `The spreadsheet ID.${spreadsheetId ? ` Default: ${spreadsheetId}` : ''}`, required: true },
        { name: 'range', type: 'string', description: 'A1 notation range (e.g. "Sheet1!A1:D10")', required: true },
      ],
    },
    {
      name: 'write_sheet_data',
      autoGenerated: true,
      description: `Write/overwrite data in a Google Sheet range. ${spreadsheetId ? `Default spreadsheet: "${spreadsheetName}" (ID: ${spreadsheetId})` : ''}`,
      url: `${base}/sheets/write?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'spreadsheetId', type: 'string', description: `The spreadsheet ID.${spreadsheetId ? ` Default: ${spreadsheetId}` : ''}`, required: true },
        { name: 'range', type: 'string', description: 'A1 notation range to write to', required: true },
        { name: 'values', type: 'array', description: 'A 2D array of values (rows of cells), e.g. [["Name","Age"],["Alice","30"]]', required: true },
      ],
    },
    {
      name: 'append_sheet_rows',
      autoGenerated: true,
      description: `Append rows to the end of data in a Google Sheet. ${spreadsheetId ? `Default spreadsheet: "${spreadsheetName}" (ID: ${spreadsheetId})` : ''}`,
      url: `${base}/sheets/append?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'spreadsheetId', type: 'string', description: `The spreadsheet ID.${spreadsheetId ? ` Default: ${spreadsheetId}` : ''}`, required: true },
        { name: 'range', type: 'string', description: 'A1 notation range (e.g. "Sheet1!A:E") to append under', required: true },
        { name: 'values', type: 'array', description: 'A 2D array of rows to append, e.g. [["Alice","30"],["Bob","25"]]', required: true },
      ],
    },
    {
      name: 'create_spreadsheet',
      autoGenerated: true,
      description: 'Create a new Google Spreadsheet.',
      url: `${base}/sheets/create?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'title', type: 'string', description: 'Title for the new spreadsheet', required: true },
      ],
    },
  ];

  return tools;
}

function buildDocsTools(userId, integrationId, documentId, documentName) {
  const qs = `userId=${userId}&integrationId=${integrationId}`;
  const base = API_BASE;

  const tools = [
    {
      name: 'list_google_docs',
      autoGenerated: true,
      description: 'Search or browse Google Docs accessible to the user.',
      url: `${base}/docs/list?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'query', type: 'string', description: 'Optional search term to filter documents by name', required: false },
      ],
    },
    {
      name: 'read_google_doc',
      autoGenerated: true,
      description: `Read the full text content of a Google Doc. ${documentId ? `Default document: "${documentName}" (ID: ${documentId})` : ''}`,
      url: `${base}/docs/read?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'documentId', type: 'string', description: `The document ID.${documentId ? ` Default: ${documentId}` : ''}`, required: true },
      ],
    },
    {
      name: 'create_google_doc',
      autoGenerated: true,
      description: 'Create a new Google Doc.',
      url: `${base}/docs/create?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'title', type: 'string', description: 'Title for the new document', required: true },
      ],
    },
    {
      name: 'append_to_google_doc',
      autoGenerated: true,
      description: `Append text to the end of a Google Doc. ${documentId ? `Default document: "${documentName}" (ID: ${documentId})` : ''}`,
      url: `${base}/docs/append?${qs}`,
      method: 'POST',
      parameters: [
        { name: 'documentId', type: 'string', description: `The document ID.${documentId ? ` Default: ${documentId}` : ''}`, required: true },
        { name: 'text', type: 'string', description: 'Text content to append', required: true },
      ],
    },
  ];

  return tools;
}

const AUTO_TOOL_NAMES = [
  'list_spreadsheets', 'get_spreadsheet_info', 'read_sheet_data',
  'write_sheet_data', 'append_sheet_rows', 'create_spreadsheet',
  'list_google_docs', 'read_google_doc', 'create_google_doc', 'append_to_google_doc',
];

// ─── Component ──────────────────────────────────────────────

export default function ChatbotEdit() {
  const { id } = useParams();
  const navigate = useNavigate();
  const isNew = !id;

  // Basic config
  const [name, setName] = useState('');
  const [systemPrompt, setSystemPrompt] = useState('');
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(!isNew);
  const [config, setConfig] = useState(null);

  // Google integrations (from calendar)
  const [integrations, setIntegrations] = useState([]);

  // Sheets config
  const [sheetsEnabled, setSheetsEnabled] = useState(false);
  const [sheetsIntegrationId, setSheetsIntegrationId] = useState('');
  const [sheetsSpreadsheetId, setSheetsSpreadsheetId] = useState('');
  const [sheetsSpreadsheetName, setSheetsSpreadsheetName] = useState('');
  const [showSheetsModal, setShowSheetsModal] = useState(false);
  const [sheetFiles, setSheetFiles] = useState([]);
  const [sheetFilesLoading, setSheetFilesLoading] = useState(false);
  const [sheetSearch, setSheetSearch] = useState('');

  // Docs config
  const [docsEnabled, setDocsEnabled] = useState(false);
  const [docsIntegrationId, setDocsIntegrationId] = useState('');
  const [docsDocumentId, setDocsDocumentId] = useState('');
  const [docsDocumentName, setDocsDocumentName] = useState('');
  const [showDocsModal, setShowDocsModal] = useState(false);
  const [docFiles, setDocFiles] = useState([]);
  const [docFilesLoading, setDocFilesLoading] = useState(false);
  const [docSearch, setDocSearch] = useState('');

  // Load Google integrations
  useEffect(() => {
    calendarAPI.getIntegrations()
      .then(({ data }) => {
        const google = (data.integrations || []).filter(i => i.provider === 'google');
        setIntegrations(google);
      })
      .catch(() => {});
  }, []);

  // Load existing chatbot config
  useEffect(() => {
    if (isNew) return;
    setLoading(true);
    api.get(`/chatbots/${id}`)
      .then(({ data }) => {
        const c = data.chatbot || data;
        setName(c.name || '');
        setSystemPrompt(c.systemPrompt || '');
        setConfig(c);

        // Restore sheets config
        if (c.sheetsConfig) {
          setSheetsEnabled(c.sheetsConfig.enabled || false);
          setSheetsIntegrationId(c.sheetsConfig.integrationId || '');
          setSheetsSpreadsheetId(c.sheetsConfig.spreadsheetId || '');
          setSheetsSpreadsheetName(c.sheetsConfig.spreadsheetName || '');
        }
        // Restore docs config
        if (c.docsConfig) {
          setDocsEnabled(c.docsConfig.enabled || false);
          setDocsIntegrationId(c.docsConfig.integrationId || '');
          setDocsDocumentId(c.docsConfig.documentId || '');
          setDocsDocumentName(c.docsConfig.documentName || '');
        }
      })
      .catch(err => console.error('Failed to load chatbot:', err))
      .finally(() => setLoading(false));
  }, [id, isNew]);

  // Fetch spreadsheet files when integration is selected
  const fetchSpreadsheets = useCallback(async (intId, query) => {
    if (!intId) return;
    setSheetFilesLoading(true);
    try {
      const { data } = await googleWorkspaceAPI.listSpreadsheets(intId, query);
      setSheetFiles(data.files || []);
    } catch (err) {
      console.error('Failed to list spreadsheets:', err);
    } finally {
      setSheetFilesLoading(false);
    }
  }, []);

  // Fetch document files when integration is selected
  const fetchDocuments = useCallback(async (intId, query) => {
    if (!intId) return;
    setDocFilesLoading(true);
    try {
      const { data } = await googleWorkspaceAPI.listDocuments(intId, query);
      setDocFiles(data.files || []);
    } catch (err) {
      console.error('Failed to list documents:', err);
    } finally {
      setDocFilesLoading(false);
    }
  }, []);

  // Auto-fetch files when modal opens or integration changes
  useEffect(() => {
    if (showSheetsModal && sheetsIntegrationId) fetchSpreadsheets(sheetsIntegrationId, sheetSearch);
  }, [showSheetsModal, sheetsIntegrationId]); // eslint-disable-line

  useEffect(() => {
    if (showDocsModal && docsIntegrationId) fetchDocuments(docsIntegrationId, docSearch);
  }, [showDocsModal, docsIntegrationId]); // eslint-disable-line

  // Debounced search
  useEffect(() => {
    if (!showSheetsModal || !sheetsIntegrationId) return;
    const t = setTimeout(() => fetchSpreadsheets(sheetsIntegrationId, sheetSearch), 400);
    return () => clearTimeout(t);
  }, [sheetSearch]); // eslint-disable-line

  useEffect(() => {
    if (!showDocsModal || !docsIntegrationId) return;
    const t = setTimeout(() => fetchDocuments(docsIntegrationId, docSearch), 400);
    return () => clearTimeout(t);
  }, [docSearch]); // eslint-disable-line

  // ─── Save handler ─────────────────────────────────────────

  async function handleSave() {
    if (!name.trim()) return;
    setSaving(true);

    try {
      // Build auto-generated tools
      let autoTools = [];

      // Get userId from the first integration (they all share the same user)
      const userId = integrations.length > 0 ? integrations[0].userId : null;

      if (sheetsEnabled && sheetsIntegrationId) {
        const integ = integrations.find(i => String(i.id) === String(sheetsIntegrationId));
        autoTools.push(...buildSheetsTools(
          integ?.userId || userId,
          sheetsIntegrationId,
          sheetsSpreadsheetId,
          sheetsSpreadsheetName,
        ));
      }

      if (docsEnabled && docsIntegrationId) {
        const integ = integrations.find(i => String(i.id) === String(docsIntegrationId));
        autoTools.push(...buildDocsTools(
          integ?.userId || userId,
          docsIntegrationId,
          docsDocumentId,
          docsDocumentName,
        ));
      }

      // Merge with any manual tools from existing config, filtering out old auto-generated ones
      const manualTools = (config?.tools || []).filter(t => !AUTO_TOOL_NAMES.includes(t.name) && !t.autoGenerated);
      const allTools = [...manualTools, ...autoTools];

      const payload = {
        name: name.trim(),
        systemPrompt,
        tools: allTools,
        sheetsConfig: {
          enabled: sheetsEnabled,
          integrationId: sheetsIntegrationId,
          spreadsheetId: sheetsSpreadsheetId,
          spreadsheetName: sheetsSpreadsheetName,
        },
        docsConfig: {
          enabled: docsEnabled,
          integrationId: docsIntegrationId,
          documentId: docsDocumentId,
          documentName: docsDocumentName,
        },
      };

      if (isNew) {
        const { data } = await api.post('/chatbots', payload);
        navigate(`/chatbots/${data.chatbot?.id || data.id}`, { replace: true });
      } else {
        await api.put(`/chatbots/${id}`, payload);
      }
    } catch (err) {
      console.error('Save failed:', err);
    } finally {
      setSaving(false);
    }
  }

  // ─── Render helpers ───────────────────────────────────────

  const glassStyle = {
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '12px',
  };

  const inputStyle = {
    background: 'rgba(255,255,255,0.06)',
    border: '1px solid rgba(255,255,255,0.10)',
    borderRadius: '8px',
    color: '#e2e8f0',
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="animate-spin" size={24} style={{ color: '#E8792F' }} />
      </div>
    );
  }

  return (
    <div className="dot-bg min-h-screen p-6">
      <div className="max-w-3xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <button
              onClick={() => navigate('/chatbots')}
              className="p-2 rounded-lg hover:bg-white/5 transition"
              style={{ color: '#94a3b8' }}
            >
              <ArrowLeft size={18} />
            </button>
            <h1 className="text-xl font-bold text-white">
              {isNew ? 'New Chatbot' : 'Edit Chatbot'}
            </h1>
          </div>
          <button
            onClick={handleSave}
            disabled={saving || !name.trim()}
            className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition disabled:opacity-50"
            style={{ background: '#E8792F', color: '#fff' }}
          >
            {saving ? <Loader2 className="animate-spin" size={16} /> : <Save size={16} />}
            Save
          </button>
        </div>

        {/* Basic Info */}
        <div className="p-5 space-y-4" style={glassStyle}>
          <div>
            <label className="block text-xs font-medium mb-1.5" style={{ color: '#94a3b8' }}>Name</label>
            <input
              value={name}
              onChange={e => setName(e.target.value)}
              placeholder="My Chatbot"
              className="w-full px-3 py-2 text-sm"
              style={inputStyle}
            />
          </div>
          <div>
            <label className="block text-xs font-medium mb-1.5" style={{ color: '#94a3b8' }}>System Prompt</label>
            <textarea
              value={systemPrompt}
              onChange={e => setSystemPrompt(e.target.value)}
              placeholder="You are a helpful assistant..."
              rows={4}
              className="w-full px-3 py-2 text-sm resize-y"
              style={inputStyle}
            />
          </div>
        </div>

        {/* Tool Integrations */}
        <div className="p-5" style={glassStyle}>
          <h2 className="text-sm font-semibold text-white mb-4">Tool Integrations</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3">
            {/* Google Sheets Button */}
            <button
              onClick={() => setShowSheetsModal(true)}
              className="flex flex-col items-center gap-2 p-4 rounded-xl transition hover:bg-white/5"
              style={{
                border: sheetsEnabled ? '2px solid #22c55e' : '1px solid rgba(255,255,255,0.08)',
                background: sheetsEnabled ? 'rgba(34,197,94,0.08)' : 'rgba(255,255,255,0.02)',
              }}
            >
              <Table2 size={24} style={{ color: sheetsEnabled ? '#22c55e' : '#64748b' }} />
              <span className="text-xs font-medium" style={{ color: sheetsEnabled ? '#22c55e' : '#94a3b8' }}>
                Sheets
              </span>
              {sheetsEnabled && <Check size={14} style={{ color: '#22c55e' }} />}
            </button>

            {/* Google Docs Button */}
            <button
              onClick={() => setShowDocsModal(true)}
              className="flex flex-col items-center gap-2 p-4 rounded-xl transition hover:bg-white/5"
              style={{
                border: docsEnabled ? '2px solid #22c55e' : '1px solid rgba(255,255,255,0.08)',
                background: docsEnabled ? 'rgba(34,197,94,0.08)' : 'rgba(255,255,255,0.02)',
              }}
            >
              <FileText size={24} style={{ color: docsEnabled ? '#22c55e' : '#64748b' }} />
              <span className="text-xs font-medium" style={{ color: docsEnabled ? '#22c55e' : '#94a3b8' }}>
                Docs
              </span>
              {docsEnabled && <Check size={14} style={{ color: '#22c55e' }} />}
            </button>
          </div>

          {/* Active tools summary */}
          {(sheetsEnabled || docsEnabled) && (
            <div className="mt-4 pt-4" style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}>
              <p className="text-xs mb-2" style={{ color: '#64748b' }}>Active auto-generated tools:</p>
              <div className="flex flex-wrap gap-1.5">
                {sheetsEnabled && (
                  <>
                    {['list_spreadsheets', 'get_spreadsheet_info', 'read_sheet_data', 'write_sheet_data', 'append_sheet_rows', 'create_spreadsheet'].map(t => (
                      <span key={t} className="text-[10px] px-2 py-0.5 rounded-full" style={{ background: 'rgba(34,197,94,0.15)', color: '#4ade80' }}>
                        {t}
                      </span>
                    ))}
                  </>
                )}
                {docsEnabled && (
                  <>
                    {['list_google_docs', 'read_google_doc', 'create_google_doc', 'append_to_google_doc'].map(t => (
                      <span key={t} className="text-[10px] px-2 py-0.5 rounded-full" style={{ background: 'rgba(59,130,246,0.15)', color: '#60a5fa' }}>
                        {t}
                      </span>
                    ))}
                  </>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Tools Preview (JSON) */}
        {config?.tools?.length > 0 && (
          <div className="p-5" style={glassStyle}>
            <h2 className="text-sm font-semibold text-white mb-3">All Tools ({config.tools.length})</h2>
            <div className="overflow-x-auto">
              <pre className="text-xs p-3 rounded-lg" style={{ background: 'rgba(0,0,0,0.3)', color: '#94a3b8', maxHeight: '200px', overflow: 'auto' }}>
                {JSON.stringify(config.tools, null, 2)}
              </pre>
            </div>
          </div>
        )}
      </div>

      {/* ─── Sheets Modal ─────────────────────────────────── */}
      {showSheetsModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60">
          <div className="w-full max-w-lg mx-4 p-6 rounded-2xl" style={{ background: '#0f1729', border: '1px solid rgba(255,255,255,0.1)' }}>
            <div className="flex items-center justify-between mb-5">
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                <Table2 size={18} style={{ color: '#22c55e' }} />
                Google Sheets Integration
              </h3>
              <button onClick={() => setShowSheetsModal(false)} className="p-1 hover:bg-white/10 rounded">
                <X size={16} style={{ color: '#94a3b8' }} />
              </button>
            </div>

            {/* Enable toggle */}
            <label className="flex items-center gap-3 mb-5 cursor-pointer">
              <div
                className="w-10 h-5 rounded-full relative transition-colors"
                style={{ background: sheetsEnabled ? '#22c55e' : 'rgba(255,255,255,0.15)' }}
                onClick={() => setSheetsEnabled(!sheetsEnabled)}
              >
                <div
                  className="absolute top-0.5 w-4 h-4 rounded-full bg-white transition-all"
                  style={{ left: sheetsEnabled ? '22px' : '2px' }}
                />
              </div>
              <span className="text-sm text-white">Enable Google Sheets tools</span>
            </label>

            {sheetsEnabled && (
              <div className="space-y-4">
                {/* Integration selector */}
                <div>
                  <label className="block text-xs font-medium mb-1.5" style={{ color: '#94a3b8' }}>Google Account</label>
                  {integrations.length === 0 ? (
                    <p className="text-xs" style={{ color: '#f87171' }}>
                      No Google accounts connected. Go to Meetings to connect one.
                    </p>
                  ) : (
                    <select
                      value={sheetsIntegrationId}
                      onChange={e => {
                        setSheetsIntegrationId(e.target.value);
                        setSheetsSpreadsheetId('');
                        setSheetsSpreadsheetName('');
                      }}
                      className="w-full px-3 py-2 text-sm rounded-lg"
                      style={inputStyle}
                    >
                      <option value="">Select account...</option>
                      {integrations.map(i => (
                        <option key={i.id} value={i.id}>{i.externalAccountId}</option>
                      ))}
                    </select>
                  )}
                </div>

                {/* Spreadsheet picker */}
                {sheetsIntegrationId && (
                  <div>
                    <label className="block text-xs font-medium mb-1.5" style={{ color: '#94a3b8' }}>
                      Default Spreadsheet <span style={{ color: '#64748b' }}>(optional)</span>
                    </label>
                    <div className="relative mb-2">
                      <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: '#64748b' }} />
                      <input
                        value={sheetSearch}
                        onChange={e => setSheetSearch(e.target.value)}
                        placeholder="Search spreadsheets..."
                        className="w-full pl-8 pr-3 py-2 text-sm rounded-lg"
                        style={inputStyle}
                      />
                    </div>
                    <div className="max-h-48 overflow-y-auto rounded-lg" style={{ border: '1px solid rgba(255,255,255,0.08)' }}>
                      {sheetFilesLoading ? (
                        <div className="flex items-center justify-center py-6">
                          <Loader2 className="animate-spin" size={18} style={{ color: '#E8792F' }} />
                        </div>
                      ) : sheetFiles.length === 0 ? (
                        <p className="text-xs text-center py-4" style={{ color: '#64748b' }}>
                          {sheetsIntegrationId ? 'No spreadsheets found' : 'Select an account first'}
                        </p>
                      ) : (
                        sheetFiles.map(f => (
                          <button
                            key={f.id}
                            onClick={() => { setSheetsSpreadsheetId(f.id); setSheetsSpreadsheetName(f.name); }}
                            className="w-full px-3 py-2 text-left text-sm flex items-center gap-2 hover:bg-white/5 transition"
                            style={{
                              color: f.id === sheetsSpreadsheetId ? '#22c55e' : '#e2e8f0',
                              background: f.id === sheetsSpreadsheetId ? 'rgba(34,197,94,0.1)' : 'transparent',
                            }}
                          >
                            <Table2 size={14} style={{ color: f.id === sheetsSpreadsheetId ? '#22c55e' : '#64748b' }} />
                            <span className="truncate flex-1">{f.name}</span>
                            {f.id === sheetsSpreadsheetId && <Check size={14} />}
                          </button>
                        ))
                      )}
                    </div>
                    {sheetsSpreadsheetId && (
                      <button
                        onClick={() => { setSheetsSpreadsheetId(''); setSheetsSpreadsheetName(''); }}
                        className="mt-2 text-xs flex items-center gap-1 hover:underline"
                        style={{ color: '#f87171' }}
                      >
                        <Trash2 size={12} /> Clear selection (AI will use list tool to find files)
                      </button>
                    )}
                  </div>
                )}

                {/* Tools summary */}
                <div className="pt-3" style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                  <p className="text-xs mb-1.5" style={{ color: '#64748b' }}>This will add 6 tools:</p>
                  <p className="text-xs" style={{ color: '#94a3b8' }}>
                    list_spreadsheets, get_spreadsheet_info, read_sheet_data, write_sheet_data, append_sheet_rows, create_spreadsheet
                  </p>
                </div>
              </div>
            )}

            <div className="flex justify-end gap-2 mt-6">
              <button
                onClick={() => setShowSheetsModal(false)}
                className="px-4 py-2 text-sm rounded-lg hover:bg-white/5 transition"
                style={{ color: '#94a3b8' }}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ─── Docs Modal ───────────────────────────────────── */}
      {showDocsModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60">
          <div className="w-full max-w-lg mx-4 p-6 rounded-2xl" style={{ background: '#0f1729', border: '1px solid rgba(255,255,255,0.1)' }}>
            <div className="flex items-center justify-between mb-5">
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                <FileText size={18} style={{ color: '#3b82f6' }} />
                Google Docs Integration
              </h3>
              <button onClick={() => setShowDocsModal(false)} className="p-1 hover:bg-white/10 rounded">
                <X size={16} style={{ color: '#94a3b8' }} />
              </button>
            </div>

            {/* Enable toggle */}
            <label className="flex items-center gap-3 mb-5 cursor-pointer">
              <div
                className="w-10 h-5 rounded-full relative transition-colors"
                style={{ background: docsEnabled ? '#3b82f6' : 'rgba(255,255,255,0.15)' }}
                onClick={() => setDocsEnabled(!docsEnabled)}
              >
                <div
                  className="absolute top-0.5 w-4 h-4 rounded-full bg-white transition-all"
                  style={{ left: docsEnabled ? '22px' : '2px' }}
                />
              </div>
              <span className="text-sm text-white">Enable Google Docs tools</span>
            </label>

            {docsEnabled && (
              <div className="space-y-4">
                {/* Integration selector */}
                <div>
                  <label className="block text-xs font-medium mb-1.5" style={{ color: '#94a3b8' }}>Google Account</label>
                  {integrations.length === 0 ? (
                    <p className="text-xs" style={{ color: '#f87171' }}>
                      No Google accounts connected. Go to Meetings to connect one.
                    </p>
                  ) : (
                    <select
                      value={docsIntegrationId}
                      onChange={e => {
                        setDocsIntegrationId(e.target.value);
                        setDocsDocumentId('');
                        setDocsDocumentName('');
                      }}
                      className="w-full px-3 py-2 text-sm rounded-lg"
                      style={inputStyle}
                    >
                      <option value="">Select account...</option>
                      {integrations.map(i => (
                        <option key={i.id} value={i.id}>{i.externalAccountId}</option>
                      ))}
                    </select>
                  )}
                </div>

                {/* Document picker */}
                {docsIntegrationId && (
                  <div>
                    <label className="block text-xs font-medium mb-1.5" style={{ color: '#94a3b8' }}>
                      Default Document <span style={{ color: '#64748b' }}>(optional)</span>
                    </label>
                    <div className="relative mb-2">
                      <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: '#64748b' }} />
                      <input
                        value={docSearch}
                        onChange={e => setDocSearch(e.target.value)}
                        placeholder="Search documents..."
                        className="w-full pl-8 pr-3 py-2 text-sm rounded-lg"
                        style={inputStyle}
                      />
                    </div>
                    <div className="max-h-48 overflow-y-auto rounded-lg" style={{ border: '1px solid rgba(255,255,255,0.08)' }}>
                      {docFilesLoading ? (
                        <div className="flex items-center justify-center py-6">
                          <Loader2 className="animate-spin" size={18} style={{ color: '#E8792F' }} />
                        </div>
                      ) : docFiles.length === 0 ? (
                        <p className="text-xs text-center py-4" style={{ color: '#64748b' }}>
                          {docsIntegrationId ? 'No documents found' : 'Select an account first'}
                        </p>
                      ) : (
                        docFiles.map(f => (
                          <button
                            key={f.id}
                            onClick={() => { setDocsDocumentId(f.id); setDocsDocumentName(f.name); }}
                            className="w-full px-3 py-2 text-left text-sm flex items-center gap-2 hover:bg-white/5 transition"
                            style={{
                              color: f.id === docsDocumentId ? '#3b82f6' : '#e2e8f0',
                              background: f.id === docsDocumentId ? 'rgba(59,130,246,0.1)' : 'transparent',
                            }}
                          >
                            <FileText size={14} style={{ color: f.id === docsDocumentId ? '#3b82f6' : '#64748b' }} />
                            <span className="truncate flex-1">{f.name}</span>
                            {f.id === docsDocumentId && <Check size={14} />}
                          </button>
                        ))
                      )}
                    </div>
                    {docsDocumentId && (
                      <button
                        onClick={() => { setDocsDocumentId(''); setDocsDocumentName(''); }}
                        className="mt-2 text-xs flex items-center gap-1 hover:underline"
                        style={{ color: '#f87171' }}
                      >
                        <Trash2 size={12} /> Clear selection (AI will use list tool to find docs)
                      </button>
                    )}
                  </div>
                )}

                {/* Tools summary */}
                <div className="pt-3" style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                  <p className="text-xs mb-1.5" style={{ color: '#64748b' }}>This will add 4 tools:</p>
                  <p className="text-xs" style={{ color: '#94a3b8' }}>
                    list_google_docs, read_google_doc, create_google_doc, append_to_google_doc
                  </p>
                </div>
              </div>
            )}

            <div className="flex justify-end gap-2 mt-6">
              <button
                onClick={() => setShowDocsModal(false)}
                className="px-4 py-2 text-sm rounded-lg hover:bg-white/5 transition"
                style={{ color: '#94a3b8' }}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
